# fly.toml app configuration file generated for finance-dashboard-app on 2023-11-21T19:14:43+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "finance-dashboard-app"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
